[versions]
agp = "8.5.1"
androidxRoomRuntime = "2.5.1"
googleApiClient = "1.34.1"
googleApiClientAndroid = "1.33.2"
googleApiServicesDrive = "v3-rev20230820-2.0.0"
googleApiServicesDriveVersion = "v3-rev305-1.25.0"
googleGoogleApiServicesDrive = "v3-rev20220811-1.32.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
materialVersion = "1.12.0"
mpandroidchart = "v3.1.0"
playServicesAuth = "21.3.0"
playServicesAuthVersion = "20.5.0"
playServicesDrive = "18.2.0"
poi = "5.2.3"
poiOoxml = "5.2.3"
roomCompiler = "2.5.1"
roomRuntime = "2.6.1"
gridlayout = "1.0.0"
xmlbeans = "5.1.1"

[libraries]
androidx-room-compiler-v251 = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-runtime-v251 = { module = "androidx.room:room-runtime", version.ref = "androidxRoomRuntime" }
apache-poi = { module = "org.apache.poi:poi", version.ref = "poi" }
apis-google-api-services-drive = { module = "com.google.apis:google-api-services-drive", version.ref = "googleApiServicesDriveVersion" }
google-api-client = { module = "com.google.api-client:google-api-client", version.ref = "googleApiClient" }
google-api-client-android = { module = "com.google.api-client:google-api-client-android", version.ref = "googleApiClient" }
google-api-client-android-v1332 = { module = "com.google.api-client:google-api-client-android", version.ref = "googleApiClientAndroid" }
google-api-services-drive = { module = "com.google.api-services:google-api-services-drive", version.ref = "googleApiServicesDrive" }
google-api-services-drive-vv3rev202208111321 = { module = "com.google.apis:google-api-services-drive", version.ref = "googleGoogleApiServicesDrive" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-v1120 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
play-services-auth-v2050 = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuthVersion" }
play-services-drive = { module = "com.google.android.gms:play-services-drive", version.ref = "playServicesDrive" }
poi-ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poiOoxml" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version.ref = "gridlayout" }
xmlbeans = { module = "org.apache.xmlbeans:xmlbeans", version.ref = "xmlbeans" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

